from cambc import Direction, EntityType, Environment


DIRECTIONS = [d for d in Direction if d != Direction.CENTRE]
ORTHOGONAL_DIRECTIONS = [Direction.NORTH, Direction.EAST, Direction.SOUTH, Direction.WEST]

PASSABLE_BUILDINGS = {
    EntityType.CORE,
    EntityType.ROAD,
    EntityType.CONVEYOR,
    EntityType.ARMOURED_CONVEYOR,
    EntityType.BRIDGE,
    EntityType.SPLITTER,
}

ORE_TYPES = {Environment.ORE_TITANIUM, Environment.ORE_AXIONITE}

RESOURCE_TITANIUM = "titanium"
RESOURCE_AXIONITE = "axionite"

MARKER_KIND_ENEMY = 1
MARKER_KIND_PHASE = 2
MARKER_KIND_ORE_TI = 3
MARKER_KIND_ORE_AX = 4

PHASE_BOOTSTRAP = 1
PHASE_EXPAND_TITANIUM = 2
PHASE_EXPAND_AXIONITE = 3
PHASE_STABILIZE = 4

TI_BUILDER_RESERVE = 30
SECOND_BUILDER_RESERVE = 90
THIRD_BUILDER_RESERVE = 120
FOURTH_BUILDER_RESERVE = 150
GUNNER_RESERVE = 80

TITANIUM_LINE_READY_HARVESTERS = 2
TITANIUM_LINE_READY_SCALE = 118.0
MAX_BUILDERS_PHASE_ONE = 4

MARKER_KIND_BASE = 1_000_000
MARKER_X_BASE = 10_000
MARKER_Y_BASE = 100

LARGE_NUMBER = 10**9

STUCK_KILL_ROUNDS = 25
MAX_IDLE_ROUNDS = 80
